export const enQWERTYLayout = {
  'q': { '⟨q⟩': 'quite' },
  'w': { 'w': 'wine', 'hw': 'whine' },
  'e': { 'ɛ': 'dress', 'iː': 'fleece'},
  'r': { 'r': 'rye' },
  't': { 't': 'tie', 'ð': 'thy', 'θ': 'thigh' },
  'y': { 'j': 'yes' },
  'u': { 'uː': 'goose', 'ʌ': 'strut'},
  'i': { 'aɪ': 'price', 'ɪ': 'kit' },
  'o': { 'ɒ': 'lot', 'aʊ': 'mouth', 'oʊ': 'goat', 'ɔː': 'thought', 'ɔɪ': 'choice', 'ʊ': 'foot' },
  'p': { 'p': 'pie' },
  'clear': null,
  'a': { 'ɑː': 'palm', 'æ': 'trap', 'eɪ': 'face' },
  's': { 's': 'sigh', 'ʃ': 'shy' },
  'd': { 'd': 'dye' },
  'f': { 'f': 'find' },
  'g': { 'g': 'guy', 'dʒ': 'giant', 'ʒ': 'beige' },
  'h': { 'h': 'high' },
  'j': { 'dʒ': 'giant', 'ʒ': 'beige' },
  'k': { 'k': 'kind' },
  'l': { 'l': 'lie' },
  'ˈ': {'ˈ': 'primary stress'},
  'backspace': null,
  'z': { 'z': 'zoo' },
  'x': { 'ks': 'exit' },
  'c': { 'k': 'crack', 'tʃ': 'catch' },
  'v': { 'v': 'vie' },
  'b': { 'b' : 'buy' },
  'n': { 'n': 'nigh', 'ŋ' : 'sang' },
  'm': { 'm': 'my' },
  'ˌ': { 'ˌ': 'secondary stress' },
  '.': { '.': 'syllable break' },
  'enter': null,
  'space': null,
  'caps': null,
};
export const enQWERTYLineBreaks = ['clear', 'backspace', 'enter'];
