export const enQWERTYLayout = {
  'q': { 'kw': 'quite' },
  'w': { 'w': 'wine', 'hw': 'whine' },
  'e': { 'ɛ': 'dress', 'iː': 'fleece', 'ər': 'letter', 'ɛr': 'merry', 'ɪər': 'near' },
  'r': { 'r': 'rye' },
  't': { 't': 'tie', 'ð': 'thy', 'θ': 'thigh' },
  'y': { 'j': 'yes', 'i': 'happy' },
  'u': { 'uː': 'goose', 'ʌ': 'strut', 'uə': 'influence', 'ʊər': 'cure', 'ɜːr': 'nurse'},
  'i': { 'aɪ': 'price', 'ɪ': 'kit', 'iə': 'California', 'ɪr': 'mirror' },
  'o': { 'ɒ': 'lot', 'aʊ': 'mouth', 'oʊ': 'goat', 'ɔː': 'thought', 'ɔɪ': 'choice', 'ʊ': 'foot', 'uː': 'goose', 'ə': 'abbot', 'ər': 'history', 'ɔːr': 'force', '	ɔɪər': 'coir', 'ʊr': 'courier', 'ʊər': 'tour' },
  'p': { 'p': 'pie' },
  '[': { '[': 'open square bracket' },
  ']': { ']': 'close square bracket' },
  'clear': null,
  'a': { 'ɑː': 'palm', 'æ': 'trap', 'eɪ': 'face', 'ə': 'comma', 'ər': 'forward' },
  's': { 's': 'sigh', 'ʃ': 'shy' },
  'd': { 'd': 'dye' },
  'f': { 'f': 'find' },
  'g': { 'g': 'guy', 'dʒ': 'giant', 'ʒ': 'beige' },
  'h': { 'h': 'high' },
  'j': { 'dʒ': 'giant', 'ʒ': 'beige' },
  'k': { 'k': 'kind' },
  'l': { 'l': 'lie', 'əl': 'bottle' },
  'ˈ': {'ˈ': 'primary stress'},
  'backspace': null,
  'z': { 'z': 'zoo' },
  'x': { 'ks': 'exit' },
  'c': { 'k': 'crack', 'tʃ': 'catch' },
  'v': { 'v': 'vie' },
  'b': { 'b' : 'buy' },
  'n': { 'n': 'nigh', 'ŋ': 'sang', 'ən': 'button' },
  'm': { 'm': 'my', 'əm': 'rhythm' },
  'ˌ': { 'ˌ': 'secondary stress' },
  '.': { '.': 'syllable break' },
  '/': { '/': 'slash' },
  'space': null,
};
export const enQWERTYLineBreaks = ['clear', 'backspace', '/'];
